services:
    PoP\Taxonomies\FieldResolvers\:
        resource: '../src/FieldResolvers/*'
        public: true

    PoP\Taxonomies\TypeResolvers\:
        resource: '../src/TypeResolvers/*'
        public: true
