parameters:
    version: '0.1.0'

services:
    _defaults:
        bind:
            PoP\Hooks\HooksAPIInterface: '@hooks_api'
            PoP\Translation\TranslationAPIInterface: '@translation_api'

    PoP\Taxonomies\Hooks\:
        resource: '../src/Hooks/*'
        public: true

    PoP\Taxonomies\Conditional\API\RouteModuleProcessors\:
        resource: '../src/Conditional/API/RouteModuleProcessors/*'
        public: true

    PoP\Taxonomies\Conditional\RESTAPI\RouteModuleProcessors\:
        resource: '../src/Conditional/RESTAPI/RouteModuleProcessors/*'
        public: true
