services:
    _defaults:
        bind:
            PoP\Hooks\HooksAPIInterface: '@hooks_api'
            PoP\Translation\TranslationAPIInterface: '@translation_api'

    PoP\Taxonomies\Conditional\CustomPosts\Conditional\RESTAPI\Hooks\:
        resource: '../../../../../src/Conditional/CustomPosts/Conditional/RESTAPI/Hooks/*'
        public: true
